version: "3.8"

services:
  n8n:
    image: n8nio/n8n
    container_name: n8n
    restart: always
    ports:
      - "5678:5678"
    environment:
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=admin
      - N8N_BASIC_AUTH_PASSWORD=yourStrongPassword
      - WEBHOOK_URL=https://${DOMAIN}/
    volumes:
      - ./data/n8n:/home/node/.n8n

  supabase-db:
    image: supabase/postgres
    container_name: supabase-db
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - ./data/supabase:/var/lib/postgresql/data

  ollama:
    image: ollama/ollama
    container_name: ollama
    restart: always
    ports:
      - "11434:11434"
    volumes:
      - ./data/ollama:/root/.ollama

  open-webui:
    image: ghcr.io/open-webui/open-webui:main
    container_name: open-webui
    restart: always
    ports:
      - "3000:3000"
    environment:
      - OLLAMA_BASE_URL=http://ollama:11434
    depends_on:
      - ollama
    volumes:
      - ./data/open-webui:/app/backend/data

  flowise:
    image: flowiseai/flowise
    container_name: flowise
    restart: always
    ports:
      - "3001:3000"
    volumes:
      - ./data/flowise:/root/.flowise

  qdrant:
    image: qdrant/qdrant
    container_name: qdrant
    restart: always
    ports:
      - "6333:6333"
    volumes:
      - ./data/qdrant:/qdrant/storage

  searxng:
    image: searxng/searxng
    container_name: searxng
    restart: always
    ports:
      - "8080:8080"
    environment:
      - BASE_URL=http://${DOMAIN}:8080/
    volumes:
      - ./data/searxng:/etc/searxng

  caddy:
    image: caddy:latest
    container_name: caddy
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - ./data/caddy_data:/data
      - ./data/caddy_config:/config

  langfuse:
    image: ghcr.io/langfuse/langfuse:latest
    container_name: langfuse
    restart: always
    ports:
      - "3002:3000"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@supabase-db:5432/postgres
    depends_on:
      - supabase-db